id: P000559
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG16610
  title: བྱང་ཆུབ་སེམས་དཔའི་ས་དང་ཚོམས་ཞེས་བྱ་བ།
  author: ''
  volumes:
    b6bf48f353ed4728b64c3c8310379152:
      image_group_id: I1KG16646
      title: Volume 1 of byang chub sems dpa'i sa dang tshoms zhes bya ba/
      volume_number: 1
      total_pages: 596
      base_file: v001.txt
